title: some person
description: some person named aaron markey. I write and complain about things.
lang: en_US
logo: /assets/images/logo-1024.png
twitter:
  username: heressomeperson
  card: summary
url: https://someperson.me
author:
  email: aaron@someperson.me
  github: aaronmarkey
  name: aaron markey
  twitter: heressomeperson


app_context:
  palettes:
    available:
      - id: hyper
        icon: "ğŸ”®"
        name: "Hyper"
      # - id: night
      #   icon: "ğŸŒ’"
      #   name: "Night"
      - id: october
        icon: "ğŸ"
        name: "October"
      - id: roses
        icon: "ğŸŒ¹"
        name: "Roses"
    default: roses
  hearts:
    - "&#x1f498;"
    - "&#x1f49d;"
    - "&#x1f496;"
    - "&#x1f497;"
    - "&#x1f493;"
    - "&#x2764;&#xfe0f;"
    - "&#x1f9e1;"
    - "&#x1f49b;"
    - "&#x1f49a;"
    - "&#x1f499;"
    - "&#x1f49c;"
    - "&#x1f90e;"
    - "&#x1f5a4;"
    - "&#x1f90d;"
  author:
    name:
      first:
        - aaron
        - a-a-ron
        - erin
        - aron
        - arin
        - airin
      last:
        - markey
        - marque
        - marky
        - markee
        - makey
        - marke

autopages:
  enabled: true
  tags:
    layouts:
      - "tag.html"
    title: ":tag stuff"
    permalink: "/stuff/:tag"

pagination:
  enabled: true
  per_page: 20
  permalink: "/page/:num/"
  sort_reverse: true

sass:
  style: compressed


plugins:
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap


exclude:
  - README.md
  - LICENSE.txt
  - mechanica-ui.gemspec
  - assets/src
  - package.json
  - package-lock.json
  - webpack.config.js
  - .nvmrc
